### ISSUE TITLE
koishi运行日志报错 TypeError: patterns is not iterable at Object.apply 

### ISSUE THREAD

**Issue by regaliastar** [lgc-KoiDev/koishi-plugin-memes-api#20]
TypeError: patterns is not iterable at Object.apply (C:\Users\admin\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\koishi-plugin-memes-api\lib\index.js:781:29)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

环境：windows
koishi: v4.18.0
koishi-plugin-memes-api: v0.1.30

**Comment by lgc2333** [comment]
related to https://github.com/lgc-KoiDev/koishi-plugin-memes-api/issues/18
