### ISSUE TITLE
能否增加【指令 @某人】的形式，用那个人的头像做图片

### ISSUE THREAD

**Issue by Haku530** [lgc-KoiDev/koishi-plugin-memes-api#24]
如题

**Comment by lgc2333** [comment]
已有

**Comment by Haku530** [comment]
![image](https://github.com/user-attachments/assets/5ff050dc-ea66-4d72-86f3-5812ed92ef5e)
这样的bug，请问怎么办

**Comment by lgc2333** [comment]
onebot协议端问题，请去对应协议端那边反馈

**Comment by Haku530** [comment]
> onebot协议端问题，请去对应协议端那边反馈

可以增加通过qq号获取到头像的方式吗https://q1.qlogo.cn/g?b=qq&nk=${uid}&s=${size}

**Comment by lgc2333** [comment]
需要获取用户的其他信息，不只是头像

**Comment by Haku530** [comment]
但是一般情况获取头像就够了，能给llonebot用户适配一下吗，拜托啦

**Comment by lgc2333** [comment]
napcat有问题吗
